-- REFRESH TOKENS TABLE
CREATE TABLE IF NOT EXISTS REFRESH_TOKENS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    TOKEN VARCHAR(500) UNIQUE NOT NULL,
    USER_ID UUID NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    CONSTRAINT FK_REFRESH_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
