-- TABLE: ACCOUNT
CREATE TABLE ACCOUNT (
	ID BIGSERIAL PRIMARY KEY,
	USER_ID UUID NOT NULL,
	TYPE VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN DEFAULT FALSE,
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);