-- TABLE: CATEGORY
CREATE TABLE CATEGORY (
    ID BIGSERIAL PRIMARY KEY,
	USER_ID UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID BIGINT NULL REFERENCES CATEGORY(ID),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_PARENT_CATEGORY_ID FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(ID),
	CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);