-- TABLE: CATEGORY
CREATE TABLE CATEGORY (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID BIGINT NULL REFERENCES CATEGORY(ID),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED BOOLEAN DEFAULT FALSE
);