CREATE TABLE LOGICAL_TRANSACTION (
	ID UUID PRIMARY KEY,
	TRANSACTION_ID UUID NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
);