CREATE TABLE LOGICAL_TRANSACTION (
	ID UUID PRIMARY KEY,
	TRANSACTION_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);