CREATE TABLE TRANSACTIONS (
	ID UUID PRIMARY KEY,
	LOGICAL_TRANSACTION_ID UUID,
	VERSION_NUMBER BIGINT NOT NULL,
	AMOUNT NUMERIC(12, 2) NOT NULL,
	NOTE TEXT,
	TRANSACTION_TYPE VARCHAR(50) NOT NULL,
	ACCOUNT_ID BIGINT NOT NULL REFERENCES ACCOUNT (ID),
	CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY (ID),
	TRANSACTION_DATETIME TIMESTAMP NOT NULL,
	CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_LOGICAL_TRANSACTION_ID FOREIGN KEY (LOGICAL_TRANSACTION_ID) REFERENCES LOGICAL_TRANSACTION(ID),
    CONSTRAINT FK_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT FK_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);