CREATE TABLE TRANSACTION (
	ID UUID PRIMARY KEY,
	LOGICAL_TRANSACTION_ID UUID,
	VERSION_NUMBER BIGINT NOT NULL,
	AMOUNT NUMERIC(12, 2) NOT NULL,
	NOTE TEXT,
	TRANSACTION_TYPE VARCHAR(50) NOT NULL,
	ACCOUNT_ID BIGINT NOT NULL REFERENCES ACCOUNT (ID),
	CATEGORY_ID BIGINT NOT NULL REFERENCES CATEGORY (ID),
	TRANSACTION_DATETIME TIMESTAMP NOT NULL,
	CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN DEFAULT FALSE
);