-- TABLE: ACCOUNT
CREATE TABLE ACCOUNT (
	ID BIGSERIAL PRIMARY KEY,
	TYPE VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BOOLEAN DEFAULT FALSE
);