
-- TABLE: BANK_ACCOUNT
CREATE TABLE BANK_ACCOUNT (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    BALANCE NUMERIC(12,2) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE
);