id uuid PRIMARY KEY DEFAULT uuid_generate_v7()

-- TABLE: TRANSACTION
CREATE TABLE TRANSACTION (
    ID BIGSERIAL PRIMARY KEY,
    AMOUNT NUMERIC(12,2) NOT NULL,
    NOTE TEXT,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL, -- E.G., CREDIT, DEBIT
    ACCOUNT_ID BIGINT REFERENCES BANK_ACCOUNT(ID),
    CATEGORY_ID BIGINT REFERENCES CATEGORY(ID),
    TRANSACTION_DATETIME TIMESTAMP NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE,
    LAST_TRANSACTION_ID BIGINT NULL REFERENCES TRANSACTION(ID)
);

--id uuid PRIMARY KEY DEFAULT uuid_generate_v7()